# Generated by Django 5.0.7 on 2024-07-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unidade', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('CPF', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=14, null=True)),
                ('telefone_emergencia', models.CharField(blank=True, max_length=14, null=True)),
                ('criado', models.DateField(auto_now_add=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidades', to='Adm.unidades')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'Funcionários',
            },
        ),
    ]
