# Generated by Django 5.0.7 on 2024-08-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0004_alter_funcionarios_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidades',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
