# Generated by Django 5.0.7 on 2024-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0006_alter_funcionarios_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
