# Generated by Django 5.0.7 on 2024-08-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faltas',
            options={'verbose_name': 'Falta', 'verbose_name_plural': 'Faltas'},
        ),
        migrations.AlterModelTable(
            name='faltas',
            table='Faltas',
        ),
    ]
