# Generated by Django 5.0.7 on 2024-08-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0002_alter_faltas_options_alter_faltas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
