# Generated by Django 5.0.7 on 2024-08-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0004_faltas_unidadefaltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faltas',
            name='UnidadeFaltas',
        ),
    ]
