# Generated by Django 5.0.7 on 2024-08-24 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0009_funcionarios_usuario_alter_funcionarios_nome'),
        ('Controle', '0006_pontoentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoentrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
    ]
