# Generated by Django 5.0.7 on 2024-08-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0009_funcionarios_usuario_alter_funcionarios_nome'),
        ('Controle', '0012_alter_pontoentrada_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoentrada',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='pontoentrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
    ]
