# Generated by Django 5.0.7 on 2024-09-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0010_alter_funcionarios_unidade_and_more'),
        ('Controle', '0014_alter_pontoentrada_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoentrada',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
    ]
