# Generated by Django 5.0.7 on 2024-09-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0015_pontoentrada_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoentrada',
            name='unidade',
        ),
    ]
