# Generated by Django 5.0.7 on 2024-09-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0010_alter_funcionarios_unidade_and_more'),
        ('Controle', '0017_pontosaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas',
            name='falta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
        migrations.AlterField(
            model_name='pontoentrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
    ]
