# Generated by Django 5.0.7 on 2024-09-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0010_alter_funcionarios_unidade_and_more'),
        ('Controle', '0018_alter_faltas_falta_alter_pontoentrada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosaida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adm.funcionarios'),
        ),
    ]
