# Generated by Django 5.0.7 on 2024-09-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0021_atrasos_atraso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atrasos',
            old_name='funcionario',
            new_name='funcionarios',
        ),
    ]
